name: "base:ffmpeg-alpine"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "**"

jobs:
  docker:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        include:
          - ffmpeg_version: "8.0"
            os: alpine
            os_version: "3.23.2"
            platforms: linux/amd64,linux/arm64,linux/arm/v7
    steps:
      - name: Set build metadata
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "BUILD_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Multi-Arch
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.alpine
          build-args: |
            BUILD_IMAGE=${{ matrix.os }}:${{ matrix.os_version }}
            BUILD_DATE=${{ matrix.CURRENT_DATE }}
            BUILD_COMMIT=${{ matrix.CURRENT_COMMIT }}
            FFMPEG_VERSION=${{ matrix.ffmpeg_version }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            sharapov/flumixa-base:ffmpeg${{ matrix.ffmpeg_version }}-${{ matrix.os }}${{ matrix.os_version }}
            sharapov/flumixa-base:ffmpeg-latest
